### ISSUE TITLE
NuGet .NET Framework 4.6 support ?

### ISSUE THREAD

**Issue by crskycode** [morphx666/CoreAudio#22]
It's should work...

**Comment by morphx666** [comment]
Not sure what you need... but yes, CoreAudio can be compiled targeting .NET 4.6

The library was [implemented in 2011](https://web.archive.org/web/20120511202755/http://software.xfx.net/netcl/mxp/news.htm#n2507), and nothing much has changed since then. So it should be a trivial task to change the targeting framework to compile it with support for any .NET version since .NET 4.0
